### ISSUE TITLE
Plugin settings are not available

### ISSUE THREAD

**Issue by denisapokin** [saylordotorg/moodle-local_discoursesso#2]
Hi! Plugin settings are not available when you uninstall a plugin from moodle and reinstall it. moodle 3.4.2 also on the admin page plugins button is missing from Settings.

**Comment by jazinheira** [comment]
Hi @denisapokin ! I'll try to recreate the issue and see what's happening. Would you be able to take a screenshot of the missing admin page plugin button?

**Comment by jazinheira** [comment]
I guess in the plugin overview?
<img width="966" alt="image" src="https://user-images.githubusercontent.com/6720891/56044796-f487a880-5d0d-11e9-86b2-fde300405646.png">

**Comment by jazinheira** [comment]
I'm closing this for now due to lack of information - after uninstalling and reinstalling the plugin (after the necessary moodle database upgrade) the settings page is showing up.

It also appears that local plugins cannot have a 'Settings' link in the plugin overview screen.
